#ifndef EDITINGENHANCEMENT_GLOBAL_H
#define EDITINGENHANCEMENT_GLOBAL_H

#include <QtGlobal>

#if defined(EDITINGENHANCEMENT_LIBRARY)
#  define EDITINGENHANCEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDITINGENHANCEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDITINGENHANCEMENT_GLOBAL_H
